model:
  frequencies: 6
  hidden_dim: 256
  num_layers: 4

dataset:
  num_samples: 102400
  batch_size: 1024

training:
  epochs: 30
  lr: 0.001

generation:
  resolution: 512
  preset: "julia" #  julia | mandelbrot | burning_ship | newton

paths:
  live: "live/"
  log: "log/"
